# Generated by Django 3.2.6 on 2023-01-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230129_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filters',
            new_name='Filter',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='filter',
            new_name='filters',
        ),
    ]
