# Generated by Django 3.2.6 on 2023-01-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230129_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
