# Generated by Django 3.2.6 on 2023-02-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
