# Generated by Django 3.2.6 on 2023-02-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230203_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='filter',
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.filter'),
        ),
    ]
